name: Weather
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  simple_location_picker: ^0.0.3
  lottie: ^0.7.0+1
  http: ^0.12.2
  flutter_icons: ^1.1.0
  intl: ^0.16.1
  google_fonts: ^1.1.2
  flutter_svg: ^0.18.1
  flutter_custom_clippers: ^1.1.2

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/svgs/